"""Live authorization, isolated imported evidence and provider audit metadata.

Existing evidence defaults to DEMO until it can be independently verified.
"""

from alembic import op
import sqlalchemy as sa

revision = "b39018d0a203"
down_revision = "a28097c9f302"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_authorizations",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("used", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("call_authorizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_call_authorizations_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "history_batches",
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=150), nullable=False),
        sa.Column("format", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "source_hash"),
    )
    with op.batch_alter_table("history_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_batches_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "history_conversations",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("is_design", sa.Boolean(), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("image_refs", sa.JSON(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["history_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("history_conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_conversations_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "blind_comparisons",
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("left_job_id", sa.String(length=36), nullable=False),
        sa.Column("right_job_id", sa.String(length=36), nullable=False),
        sa.Column("personal_side", sa.String(length=5), nullable=False),
        sa.Column("choice", sa.String(length=10), nullable=True),
        sa.Column("voted_at", sa.Float(), nullable=True),
        sa.Column("mode", sa.String(length=12), server_default="DEMO", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blind_comparisons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blind_comparisons_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "history_cards",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.String(length=150), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("text", sa.String(length=1500), nullable=False),
        sa.Column("feature", sa.String(length=80), nullable=True),
        sa.Column("direction", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("context_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source_role", sa.String(length=30), nullable=False),
        sa.Column("image_refs", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["history_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["history_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "fingerprint"),
    )
    with op.batch_alter_table("history_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_cards_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "capability_checks",
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("capability", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["provider_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["call_authorizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("capability_checks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_capability_checks_workspace_id"), ["workspace_id"], unique=False)

    with op.batch_alter_table("preference_evidence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mode", sa.String(length=12), server_default="DEMO", nullable=False))
        batch_op.add_column(sa.Column("history_card_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("source", sa.JSON(), server_default="{}", nullable=False))
        batch_op.alter_column("review_id", existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.create_unique_constraint("uq_evidence_history_card", ["history_card_id"])
        batch_op.create_foreign_key("fk_evidence_history_card", "history_cards", ["history_card_id"], ["id"])

    with op.batch_alter_table("provider_attempts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("capability", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("duration_ms", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("input_hash", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("output_hash", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("input_versions", sa.JSON(), server_default="{}", nullable=False))

    # ### end Alembic commands ###
    # Old paid jobs require new scoped grants; never replay on upgrade.
    connection = op.get_bind()
    jobs = sa.table("jobs", sa.column("id"), sa.column("snapshot", sa.JSON()), sa.column("status"))
    steps = sa.table("steps", sa.column("job_id"), sa.column("status"), sa.column("error_code"))
    for row in connection.execute(sa.select(jobs.c.id, jobs.c.snapshot)):
        if row.snapshot.get("route", {}).get("provider") == "openai":
            connection.execute(
                jobs.update()
                .where(jobs.c.id == row.id, jobs.c.status.in_(["QUEUED", "RUNNING"]))
                .values(status="PAUSED_CREDENTIAL")
            )
            connection.execute(
                steps.update()
                .where(steps.c.job_id == row.id, steps.c.status.in_(["QUEUED", "RUNNING", "BLOCKED"]))
                .values(status="PAUSED_CREDENTIAL", error_code="LIVE_NOT_AUTHORIZED")
            )
    # Existing keys are retained for an explicit rebind decision, but cannot authorize new spend.
    op.execute("UPDATE credentials SET active = false")
    op.execute("DELETE FROM login_sessions")
    op.execute("UPDATE schedules SET enabled = false")
    op.execute("UPDATE provider_attempts SET status='OUTCOME_UNKNOWN' WHERE provider='openai' AND status='STARTED'")
    op.execute(
        "UPDATE steps SET status='OUTCOME_UNKNOWN', error_code='OUTCOME_UNKNOWN' WHERE id IN (SELECT step_id FROM provider_attempts WHERE status='OUTCOME_UNKNOWN')"
    )


def downgrade():
    raise RuntimeError(
        "0.2 experience and audit data cannot be safely downgraded; restore a pre-upgrade backup into a new directory"
    )
